config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# URL /customers/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/' => 'homes#top'
    resources :users
    resources :friends
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
  namespace :public, path: "" do
    get '/' => 'friends#index'
    get '/user/withdraw' => 'users#withdraw'
    resources :users, only: [:edit, :show, :update]
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    resources :friends do
      collection do
        get 'is_rank'
        get 'is_normal'
        get 'is_beginner'
        get 'is_coaching'
        get 'is_coached'
        get 'is_clash'
      end
    end
  end

end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to  :user

  enum favorite_champion: { aatrox: 0, ahri: 1, akali: 2, akshan: 3, alistar: 4, amumu: 5, anivia: 6, annie: 7, aphelios: 8, ashe: 9, aurelion_sol: 10, azir: 11, bard: 12, belveth: 13, blitzcrank: 14, brand: 15, braum: 16,
                            caitlyn: 17, camille: 18, cassiopea: 19, chogath: 20, corki: 21, darius: 22, diana: 23, dr_mundo: 24, draven: 25, ekko: 26, elise: 27, evelynn: 28, ezreal: 29, fiddlesticks: 30, fiora: 31, fizz: 32,
                            galio: 33, gangplank: 34, garen: 35, gnar: 36, gragas: 37, graves: 38, gwen: 39, hecarim: 40, heimerdinger: 41, illaoi: 42, irellia: 43, ivern: 44, janna: 45, jarvan_iv: 46, jax: 47, jayce: 48, jhin: 49,
                            jinx: 50, kaisa: 51, kalista: 52, karma: 53, karthus: 54, kassadin: 55, katarina: 56, kayle: 57, kayn: 58, kennen: 59, khazix: 60, kindred: 61, kled: 62, kogmaw: 63, leblanc: 64, leesin: 65, leona: 66,
                            lillia: 67, lissandra: 68, lucian: 69, lulu: 70, lux: 71, malphite: 72, malzahar: 73, maokai: 74, master_yi: 75, miss_fortune: 76, mordekaiser: 77, morgana: 78, nami: 79, nasus: 80, nautilus: 81, neeko: 82,
                            nidalee: 83, nocturne: 84, nunu: 85, olaf: 86, orianna: 87, ornn: 88, pantheon: 89, poppy: 90, pyke: 91, qiyana: 92, quinn: 93, rakan: 94, rammus: 95, reksai: 96, rell: 97, renata_glasc: 98, renekton: 99,
                            rengar: 100, riven: 101, rumble: 102, ryze: 103, samira: 104, sejuani: 105, senna: 106, seraphine: 107, sett: 108, shaco: 109, shen: 110, shyvana: 111, singed: 112, sion: 113, sivir: 114, skarner: 115,
                            sona: 116, soraka: 117, swain: 118, sylas: 119, syndra: 120, tahm_kench: 121, taliyah: 122, talon: 123, taric: 124, teemo: 125, thresh: 126, tristana: 127, trundle: 128, tryndamere: 129, twisted_fate: 130,
                            twitch: 131, udyr: 132, urgot: 133, varus: 134, vayne: 135, veiger: 136, velkoz: 137, vex: 138, vi: 139, viego: 140, viktor: 141, vladmir: 142, volibear: 143, warwick: 144, wukong: 145, xayah: 146, xerath: 147,
                            xin_zhao: 148, yasuo: 149, yone: 150, yorick: 151, yuumi: 152, zac: 153, zed: 154, zeri: 155, ziggs: 156, zilean: 157, zoe: 158, zyra: 159 }, _prefix: true

  enum favorite_champion2: { aatrox: 0, ahri: 1, akali: 2, akshan: 3, alistar: 4, amumu: 5, anivia: 6, annie: 7, aphelios: 8, ashe: 9, aurelion_sol: 10, azir: 11, bard: 12, belveth: 13, blitzcrank: 14, brand: 15, braum: 16,
                            caitlyn: 17, camille: 18, cassiopea: 19, chogath: 20, corki: 21, darius: 22, diana: 23, dr_mundo: 24, draven: 25, ekko: 26, elise: 27, evelynn: 28, ezreal: 29, fiddlesticks: 30, fiora: 31, fizz: 32,
                            galio: 33, gangplank: 34, garen: 35, gnar: 36, gragas: 37, graves: 38, gwen: 39, hecarim: 40, heimerdinger: 41, illaoi: 42, irellia: 43, ivern: 44, janna: 45, jarvan_iv: 46, jax: 47, jayce: 48, jhin: 49,
                            jinx: 50, kaisa: 51, kalista: 52, karma: 53, karthus: 54, kassadin: 55, katarina: 56, kayle: 57, kayn: 58, kennen: 59, khazix: 60, kindred: 61, kled: 62, kogmaw: 63, leblanc: 64, leesin: 65, leona: 66,
                            lillia: 67, lissandra: 68, lucian: 69, lulu: 70, lux: 71, malphite: 72, malzahar: 73, maokai: 74, master_yi: 75, miss_fortune: 76, mordekaiser: 77, morgana: 78, nami: 79, nasus: 80, nautilus: 81, neeko: 82,
                            nidalee: 83, nocturne: 84, nunu: 85, olaf: 86, orianna: 87, ornn: 88, pantheon: 89, poppy: 90, pyke: 91, qiyana: 92, quinn: 93, rakan: 94, rammus: 95, reksai: 96, rell: 97, renata_glasc: 98, renekton: 99,
                            rengar: 100, riven: 101, rumble: 102, ryze: 103, samira: 104, sejuani: 105, senna: 106, seraphine: 107, sett: 108, shaco: 109, shen: 110, shyvana: 111, singed: 112, sion: 113, sivir: 114, skarner: 115,
                            sona: 116, soraka: 117, swain: 118, sylas: 119, syndra: 120, tahm_kench: 121, taliyah: 122, talon: 123, taric: 124, teemo: 125, thresh: 126, tristana: 127, trundle: 128, tryndamere: 129, twisted_fate: 130,
                            twitch: 131, udyr: 132, urgot: 133, varus: 134, vayne: 135, veiger: 136, velkoz: 137, vex: 138, vi: 139, viego: 140, viktor: 141, vladmir: 142, volibear: 143, warwick: 144, wukong: 145, xayah: 146, xerath: 147,
                            xin_zhao: 148, yasuo: 149, yone: 150, yorick: 151, yuumi: 152, zac: 153, zed: 154, zeri: 155, ziggs: 156, zilean: 157, zoe: 158, zyra: 159 }, _prefix: true

  enum fovorite_champion3: { aatrox: 0, ahri: 1, akali: 2, akshan: 3, alistar: 4, amumu: 5, anivia: 6, annie: 7, aphelios: 8, ashe: 9, aurelion_sol: 10, azir: 11, bard: 12, belveth: 13, blitzcrank: 14, brand: 15, braum: 16,
                            caitlyn: 17, camille: 18, cassiopea: 19, chogath: 20, corki: 21, darius: 22, diana: 23, dr_mundo: 24, draven: 25, ekko: 26, elise: 27, evelynn: 28, ezreal: 29, fiddlesticks: 30, fiora: 31, fizz: 32,
                            galio: 33, gangplank: 34, garen: 35, gnar: 36, gragas: 37, graves: 38, gwen: 39, hecarim: 40, heimerdinger: 41, illaoi: 42, irellia: 43, ivern: 44, janna: 45, jarvan_iv: 46, jax: 47, jayce: 48, jhin: 49,
                            jinx: 50, kaisa: 51, kalista: 52, karma: 53, karthus: 54, kassadin: 55, katarina: 56, kayle: 57, kayn: 58, kennen: 59, khazix: 60, kindred: 61, kled: 62, kogmaw: 63, leblanc: 64, leesin: 65, leona: 66,
                            lillia: 67, lissandra: 68, lucian: 69, lulu: 70, lux: 71, malphite: 72, malzahar: 73, maokai: 74, master_yi: 75, miss_fortune: 76, mordekaiser: 77, morgana: 78, nami: 79, nasus: 80, nautilus: 81, neeko: 82,
                            nidalee: 83, nocturne: 84, nunu: 85, olaf: 86, orianna: 87, ornn: 88, pantheon: 89, poppy: 90, pyke: 91, qiyana: 92, quinn: 93, rakan: 94, rammus: 95, reksai: 96, rell: 97, renata_glasc: 98, renekton: 99,
                            rengar: 100, riven: 101, rumble: 102, ryze: 103, samira: 104, sejuani: 105, senna: 106, seraphine: 107, sett: 108, shaco: 109, shen: 110, shyvana: 111, singed: 112, sion: 113, sivir: 114, skarner: 115,
                            sona: 116, soraka: 117, swain: 118, sylas: 119, syndra: 120, tahm_kench: 121, taliyah: 122, talon: 123, taric: 124, teemo: 125, thresh: 126, tristana: 127, trundle: 128, tryndamere: 129, twisted_fate: 130,
                            twitch: 131, udyr: 132, urgot: 133, varus: 134, vayne: 135, veiger: 136, velkoz: 137, vex: 138, vi: 139, viego: 140, viktor: 141, vladmir: 142, volibear: 143, warwick: 144, wukong: 145, xayah: 146, xerath: 147,
                            xin_zhao: 148, yasuo: 149, yone: 150, yorick: 151, yuumi: 152, zac: 153, zed: 154, zeri: 155, ziggs: 156, zilean: 157, zoe: 158, zyra: 159 }, _prefix: true

  enum vc_status: { unavailable: 0, listening_only: 1, available: 2 }, _prefix: true

  enum rank: { unrank: 0, iron: 1, bronze: 2, silver: 3, gold: 4, platinum: 5, diamond: 6, master: 7, grand_master: 8, challenger: 9 }, _prefix: true

  validates :introduction, :active_time, presence: true
  validates :introduction, length: { maximum: 500 }

end

app/controllers/admin/friends_controller.rb
class Admin::FriendsController < ApplicationController
   before_action :authenticate_admin!

   def index
     @friends = Friend.all
   end

   def edit
     @friend = Friend.find(params[:id])
   end

   def update
     @friend = Friend.find(params[:id])
      if @friend.update(friend_params)
        flash[:notice] = "更新しました"
        redirect_to admin_path
      else
        render "edit"
      end
   end


  private

  def friend_params
    params.require(:friend).permit(:user_id, :favorite_champion, :favorite_champion2, :fovorite_champion3, :introduction, :rank, :is_rank, :is_normal, :is_beginner, :is_coaching, :is_coached, :is_clash, :good_at_top, :good_at_jg, :good_at_mid, :good_at_adc, :good_at_sup, :bad_at_top, :bad_at_jg, :bad_at_mid, :bad_at_adc, :bad_at_sup, :active_time, :twitter, :vc_status, :vc_discord, :vc_skype, :vc_leaguevoice)
  end

end

app/helpers/admin/friends_helper.rb
module Admin::FriendsHelper
end

app/views/admin/friends/edit.html.erb
<div class="container-fluid">

  <div class="col-12 col-md-8 col-lg-6 col-xl-4 mx-auto mt-3">
    <h2 class="mt-3">投稿編集</h2>
    <% if @friend.errors.any? %>
    <%= @friend.errors.count %>件のエラーが発生しました
    <ul>
    <% @friend.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>

    <%= form_with model: @friend, url: admin_friend_path(@friend), method: :patch do |f| %>
    <table class="table mt-3">
      <tr>
        <td>好きなチャンピオン(1体目)</td>
        <td>
          <%= f.select :favorite_champion, Friend.favorite_champions.keys.map {|k| [I18n.t("enums.friend.favorite_champions.#{k}"), k]}, {}, class: "form-select" %>
        </td>
      </tr>
      <tr>
        <td>好きなチャンピオン(2体目)</td>
        <td>
          <%= f.select :favorite_champion2, Friend.favorite_champion2s.keys.map {|k| [I18n.t("enums.friend.favorite_champion2s.#{k}"), k]}, {}, class: "form-select" %>
        </td>
      </tr>
      <tr>
        <td>好きなチャンピオン(3体目)</td>
        <td>
          <%= f.select :fovorite_champion3, Friend.fovorite_champion3s.keys.map {|k| [I18n.t("enums.friend.fovorite_champion3s.#{k}"), k]}, {}, class: "form-select" %>
        </td>
      </tr>
      <tr>
        <td>自己紹介(500文字まで)</td>
        <td><%= f.text_area :introduction, class: "form-control" %></td>
      </tr>
      <tr>
        <td>ランク</td>
        <td><%= f.select :rank, Friend.ranks.keys.map {|k| [I18n.t("enums.friend.ranks.#{k}"), k]}, {}, class: "form-select" %></td>
      </tr>
      <tr>
        <td>募集目的</td>
        <td>
          <%= f.check_box :is_rank, class: "form-check-input" %>
          <%= f.label "ランク", class: "form-check-label me-2" %>
          <%= f.check_box :is_normal, class: "form-check-input" %>
          <%= f.label "ノーマル", class: "form-check-label me-2" %>
          <%= f.check_box :is_beginner, class: "form-check-input" %>
          <%= f.label "初心者", class: "form-check-label me-2" %><br />
          <%= f.check_box :is_coaching, class: "form-check-input" %>
          <%= f.label "コーチングしたい", class: "form-check-label me-2" %>
          <%= f.check_box :is_coached, class: "form-check-input" %>
          <%= f.label "コーチングを受けたい", class: "form-check-label me-2" %>
          <%= f.check_box :is_clash, class: "form-check-input" %>
          <%= f.label "Clash", class: "form-check-label" %>
        </td>
      </tr>
      <tr>
        <td>得意なレーン</td>
        <td>
          <%= f.check_box :good_at_top, class: "form-check-input" %>
          <%= f.label "TOP", class: "form-check-label me-2" %>
          <%= f.check_box :good_at_jg, class: "form-check-input" %>
          <%= f.label "JG", class: "form-check-label me-2" %>
          <%= f.check_box :good_at_mid, class: "form-check-input" %>
          <%= f.label "MID", class: "form-check-label me-2" %>
          <%= f.check_box :good_at_adc, class: "form-check-input" %>
          <%= f.label "ADC", class: "form-check-label me-2" %>
          <%= f.check_box :good_at_sup, class: "form-check-input" %>
          <%= f.label "SUP", class: "form-check-label" %>
        </td>
      </tr>
      <tr>
        <td>苦手なレーン</td>
        <td>
          <%= f.check_box :bad_at_top, class: "form-check-input" %>
          <%= f.label "TOP", class: "form-check-label me-2" %>
          <%= f.check_box :bad_at_jg, class: "form-check-input" %>
          <%= f.label "JG", class: "form-check-label me-2" %>
          <%= f.check_box :bad_at_mid, class: "form-check-input" %>
          <%= f.label "MID", class: "form-check-label me-2" %>
          <%= f.check_box :bad_at_adc, class: "form-check-input" %>
          <%= f.label "ADC", class: "form-check-label me-2" %>
          <%= f.check_box :bad_at_sup, class: "form-check-input" %>
          <%= f.label "SUP", class: "form-check-label" %>
        </td>
      </tr>
      <tr>
        <td>活動時間帯</td>
        <td><%= f.text_field :active_time, class: "form-control" %></td>
      </tr>
      <tr>
        <td>Twitter(未記入可)</td>
        <td><%= f.text_field :twitter, class: "form-control" %></td>
      </tr>
      <tr>
        <td>ボイスチャット</td>
        <td>
          <%= f.radio_button :vc_status, "unavailable", class: "form-check-input" %>
          <%= f.label "VC不可", class: "form-check-label me-2" %>
          <%= f.radio_button :vc_status, "listening_only", class: "form-check-input" %>
          <%= f.label "聴き専", class: "form-check-label me-2" %>
          <%= f.radio_button :vc_status, "available", class: "form-check-input" %>
          <%= f.label "VC可能", class: "form-check-label me-2" %>
        </td>
      </tr>
      <tr>
        <td>利用可能なボイスチャット</td>
        <td>
          <%= f.check_box :vc_discord, class: "form-check-input" %>
          <%= f.label "Discord", class: "form-check-label me-2" %>
          <%= f.check_box :vc_skype, class: "form-check-input" %>
          <%= f.label "Skype", class: "form-check-label me-2" %>
          <%= f.check_box :vc_leaguevoice, class: "form-check-input" %>
          <%= f.label "リーグボイス", class: "form-check-label" %>
        </td>
      </tr>

    </table>

    <div class="text-center"><%= f.submit "反映", class: "btn btn-success me-3" %><%= link_to "投稿削除", public_friend_path(@friend), method: :delete, class: "btn btn-danger me-3",data: { confirm: "【確認】投稿を削除してもよろしいですか？" } %><%= link_to "戻る", :back, class: "btn btn-secondary" %></div>
    <% end %>
  </div>
</div>

app/views/admin/friends/index.html.erb
<div class="container-fluid">
  <h2>投稿一覧</h2>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @friends.each do |friend| %>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">自己紹介</h5>
          <p class="card-text">
          <% if friend.user.profile_image.attached? %>
            <%= image_tag friend.user.profile_image, size: "64x64", class: "rounded-circle me-2" %>
          <% else %>
            <%= image_tag asset_path("no_image.jpg"), size: "64x64", class: "rounded-circle me-2" %>
          <% end %><%= friend.introduction %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>サモナーネーム:　</strong><% if friend.user.is_published == "closed" %>非公開<% elsif friend.user.is_published == "limited" %>相互フォローにのみ公開<% else %><%= friend.user.summoner_name %><% end %></li>
          <li class="list-group-item"><strong>好きなチャンピオン:　</strong><%= friend.favorite_champion_i18n %>　<%= friend.favorite_champion2_i18n %>　<%= friend.fovorite_champion3_i18n %></li>
          <li class="list-group-item"><strong>ランク:　</strong><%= friend.rank_i18n %></li>
          <li class="list-group-item"><strong>募集目的:　</strong>
            <% if friend.is_rank == true %>ランク　<% end %>
            <% if friend.is_normal == true %>ノーマル　<% end %>
            <% if friend.is_beginner == true %>初心者　<% end %>
            <% if friend.is_coaching == true %>コーチングをしたい　<% end %>
            <% if friend.is_coached == true %>コーチングを受けたい　<% end %>
            <% if friend.is_clash == true %>Clash　<% end %>
          </li>
          <li class="list-group-item"><strong>得意なレーン:　</strong>
            <% if friend.good_at_top == true %>TOP　<% end %>
            <% if friend.good_at_jg == true %>JG　<% end %>
            <% if friend.good_at_mid == true %>MID　<% end %>
            <% if friend.good_at_adc == true %>ADC　<% end %>
            <% if friend.good_at_sup == true %>SUP　<% end %>
          </li>
          <li class="list-group-item"><strong>苦手なレーン:　</strong>
            <% if friend.bad_at_top == true %>TOP　<% end %>
            <% if friend.bad_at_jg == true %>JG　<% end %>
            <% if friend.bad_at_mid == true %>MID　<% end %>
            <% if friend.bad_at_adc == true %>ADC　<% end %>
            <% if friend.bad_at_sup == true %>SUP　<% end %>
          </li>
          <li class="list-group-item"><strong>活動時間帯:　</strong><%= friend.active_time %></li>
          <li class="list-group-item"><strong>Twitter:　</strong><%= friend.twitter %></li>
          <li class="list-group-item"><strong>ボイスチャット利用:　</strong><% if friend.vc_status == "unavailable" %>VC不可<% elsif friend.vc_status == "listening_only" %>聴き専<% else %>VC可能<% end %></li>
          <li class="list-group-item"><strong>利用可能なボイスチャット:　</strong><% if friend.vc_status != "unavailable" %><% if friend.vc_discord == true %>Discord　<% end %><% if friend.vc_skype == true %>Skype　<% end %><% if friend.vc_leaguevoice == true %>リーグボイス<% end %><% end %></li>
          <li class="list-group-item"><strong>最終ログイン日時：　</strong><%= friend.user.current_sign_in_at.strftime('%Y/%m/%d %R') %></li>
        </ul>

        <p class="card-text text-center"><%= link_to "編集する", edit_admin_friend_path(friend), class: "btn btn-success" %></p>

      </div>
    </div>
    <% end %>

  </div>

</div>