config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# URL /customers/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/' => 'homes#top'
    resources :users
    resources :friends
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
  namespace :public, path: "" do
    get '/' => 'friends#index'
    get '/user/withdraw' => 'users#withdraw'
    resources :users, only: [:edit, :show, :update]
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    resources :friends do
      collection do
        get 'is_rank'
        get 'is_normal'
        get 'is_beginner'
        get 'is_coaching'
        get 'is_coached'
        get 'is_clash'
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">

        <li class="nav-item">
          <a class="nav-link text-muted" href="#">フレンド検索</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-muted" href="#">コミュニティーボード</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-muted" href="#">サークル</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-muted" href="#">League of Friendsについて</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-muted" href="#">お問い合わせ</a>
        </li>

    </ul>
    <p class="text-center text-muted">
      League of Friendsは、ライアットゲームズが公式承認するものではなく、ライアットゲームズ又はリーグ・オブレジェンドの製作・管理に正式に関与したいかなる者の見解・意見に基づくものではありません。<br />
      リーグ・オブ・レジェンド及びライアットゲームズは、Riot Games,Incの商標または登録商標です。　リーグ・オブ・レジェンド &copy; Riot Games, Inc <br />
      &copy; 2022 League of Friends
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="p-3 text-bg-dark bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "フレンド募集一覧", public_friends_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "コミュニティーボード", "#", class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "サークル", "#", class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "League of Friendsについて", "#", class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "お問い合わせ", "#", class: "nav-link px-2 text-white" %></li>
        </ul>

        <% if user_signed_in? %>
        <div class="dropdown text-end text-white me-2">
          <a href="#" class="d-block text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">

          <% if @user.profile_image.attached? %>
            <%= image_tag @user.profile_image, size: "32x32", class: "rounded-circle me-2" %>
          <% else %>
            <%= image_tag asset_path("no_image.jpg"), size: "32x32", class: "rounded-circle me-2" %>
          <% end %>
          <%= current_user.summoner_name %></a>


          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><%= link_to "プロフィール", public_user_path(current_user.id), class: "dropdown-item" %></li>
            <li><%= link_to "フレンド募集", new_public_friend_path, class: "dropdown-item" %></li>
            <li><%= link_to "フォロー・フォロワー一覧", "#", class: "dropdown-item" %></li>
            <li><%= link_to "ダイレクトメッセージ", "#", class: "dropdown-item" %></li>
            <li><%= link_to "マイサークル", "#", class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </div>

        <% else %>

        <%= link_to "サインイン", new_user_session_path, class: "btn btn-outline-light me-2" %>
        <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-warning" %>

        <% end %>

      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lolfriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="text-center"><p id="notice"><%= notice %></p><p id="alert alert-info"><%= alert %></p></div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>